export const IpcChannel = {
  AuthCheck: 'auth:check',
  LinearFetchIssues: 'linear:fetch-issues',
  LinearFetchIssueDetail: 'linear:fetch-issue-detail',
  LinearFetchTeamTriage: 'linear:fetch-team-triage',
  LinearGetViewerId: 'linear:get-viewer-id',
  LinearRefresh: 'linear:refresh',
  CommentsFetch: 'comments:fetch',
  CommentsGenerateSummary: 'comments:generate-summary',
  SpecGenerate: 'spec:generate',
  SpecLaunchReview: 'spec:launch-review',
  SpecStreamChunk: 'spec:stream-chunk',
  SpecGenerateDone: 'spec:generate-done',
  SpecGenerateError: 'spec:generate-error',
  SpecPhase: 'spec:phase',
  SpecGet: 'spec:get',
  SpecWrite: 'spec:write',
  TriageGenerate: 'triage:generate',
  TriageStreamChunk: 'triage:stream-chunk',
  TriageGenerateDone: 'triage:generate-done',
  TriageGenerateError: 'triage:generate-error',
  TriagePhase: 'triage:phase',
  TriageGet: 'triage:get',
  TriageWrite: 'triage:write',
  ConfigGet: 'config:get',
  ConfigSet: 'config:set',
} as const;

export type IpcChannelName = (typeof IpcChannel)[keyof typeof IpcChannel];
